version: '3.8'

services:
  # Production Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: acquisitions-app-prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      # Mount logs directory only (no source code mounting in production)
      - ./logs:/app/logs
    networks:
      - neon-prod-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:exec,nosuid,size=100M
      - /app/logs:exec,nosuid,size=100M

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: acquisitions-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      app:
        condition: service_healthy
    networks:
      - neon-prod-network
    restart: always
    profiles:
      - with-nginx

networks:
  neon-prod-network:
    driver: bridge
    name: acquisitions-prod-network

volumes:
  logs:
    driver: local