version: '3.8'

services:
  # Neon Local Proxy - Creates ephemeral database branches
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    networks:
      - neon-dev-network
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 5432 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-dev
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src:cached
      - ./package.json:/app/package.json:cached
      - ./drizzle.config.js:/app/drizzle.config.js:cached
      # Mount logs directory
      - ./logs:/app/logs:cached
      # Exclude node_modules from host mount
      - /app/node_modules
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - neon-dev-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  neon-dev-network:
    driver: bridge
    name: acquisitions-dev-network

volumes:
  logs:
    driver: local